services:
    - type: web
      name: fastapi-backend
      runtime: python
      buildCommand: |
          cd api
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-root
      startCommand: "uvicorn main:app --host=0.0.0.0 --port=10000"
      workingDir: api
      plan: free
      autoDeploy: true
